name: asr4trailer_voice
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - portaudio
  - ffmpeg
  - pyyaml
  - rospkg
  - catkin_pkg
  - pip:
      - sounddevice>=0.4.6
      - vosk>=0.3.45
      - openai>=1.30.0
      - socksio>=1.0.0
